In [1]:
# Import required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [2]:
#Load the data
df_tra = pd.read_csv(r"C:\Users\Student\Desktop\Assignment 4\optdigits (1).tra", header=None)
df_tes = pd.read_csv(r"C:\Users\Student\Desktop\Assignment 4\optdigits (1).tes", header=None)

df_tra_6 = df_tra[df_tra[64]==6]
df_tra_9 = df_tra[df_tra[64]==9]

df_tes_6 = df_tes[df_tes[64]==6]
df_tes_9 = df_tes[df_tes[64]==9]

df_tra_data = df_tra_6.append(df_tra_9) 
df_tes_data = df_tes_6.append(df_tes_9)

In [3]:
df_tra_data.describe().transpose()

count       mean       std  min   25%   50%   75%   max
0   759.0   0.000000  0.000000  0.0   0.0   0.0   0.0   0.0
1   759.0   0.077734  0.345368  0.0   0.0   0.0   0.0   3.0
2   759.0   3.703557  3.935546  0.0   0.0   2.0   6.0  16.0
3   759.0  11.403162  3.763916  0.0   9.0  12.0  14.0  16.0
4   759.0   9.909091  5.066149  0.0   6.0  11.0  14.0  16.0
..    ...        ...       ...  ...   ...   ...   ...   ...
60  759.0  13.231884  3.764364  0.0  12.0  15.0  16.0  16.0
61  759.0   9.840580  5.594677  0.0   6.0  12.0  15.0  16.0
62  759.0   3.488801  4.319627  0.0   0.0   1.0   6.0  16.0
63  759.0   0.134387  0.679799  0.0   0.0   0.0   0.0   8.0
64  759.0   7.509881  1.500957  6.0   6.0   9.0   9.0   9.0

[65 rows x 8 columns]

In [4]:
X = df_tra_data.drop(6,axis=1)
y = df_tra_data[6]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# Fit only to the training data
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [5]:
# Now apply the transformations to the data:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(13,13,13),max_iter=500)

mlp.fit(X_train,y_train)

C:\Users\Student\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(13, 13, 13), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=500,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [6]:
predictions = mlp.predict(X_test)

from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))

[[158   1   0   0   1   2   0   0   0   0   0   0   0   0]
 [  1   2   1   1   0   0   0   0   0   0   0   0   0   0]
 [  1   0   2   1   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   1   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   1   0   0   1   0   1   0   0   0   2   0]
 [  0   0   1   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   1   0   0   0   1   0   0   0   0   1   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   2   1   0   0   0   0   0   1   0   0   1]
 [  0   0   0   0   0   0   0   0   1   0   0   0   1   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   1   1   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]]


In [7]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98       162
           1       0.67      0.40      0.50         5
           2       0.40      0.50      0.44         4
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         0
           5       0.00      0.00      0.00         5
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         3
           8       0.00      0.00      0.00         0
           9       0.00      0.00      0.00         5
          10       0.00      0.00      0.00         2
          11       0.00      0.00      0.00         0
          12       0.25      0.50      0.33         2
          14       0.00      0.00      0.00         0

    accuracy                           0.86       190
   macro avg       0.16      0.17      0.16       190
weighted avg       0.87      0.86      0.86       190



C:\Users\Student\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Student\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [8]:
print(len(mlp.coefs_))
print(len(mlp.coefs_[0]))
print(len(mlp.intercepts_[0]))

4
64
13
